<?php
namespace CP\Filter;

/**
 * LR parser generated by the Syntax tool.
 *
 * https://www.npmjs.com/package/syntax-cli
 *
 *   npm install -g syntax-cli
 *
 *   syntax-cli --help
 *
 * To regenerate run:
 *
 *   syntax-cli \
 *     --grammar ~/path-to-grammar-file \
 *     --mode <parsing-mode> \
 *     --output ~/ParserClassName.php
 */



/**
 * Default exception for syntax errors.
 */
class SyntaxException extends \Exception {}

/**
 * `yy` is a storage which semantic actions may use to
 * store needed intermediate results or state, which can be
 * accessed accross semantic actions, and in the tokenizer.
 *
 * It also exposes access to the tokenizer, so semantic actions
 * can change its state.
 */
final class yy {
  /**
   * Tokenizer instance.
   */
  public static $tokenizer = null;

  /**
   * Alias of the tokenizer instance.
   */
  public static $lexer = null;

  /**
   * User-level storage.
   */
  private static $storage = array();

  public function set($name, $value) {
    self::$storage[$name] = $value;
  }

  public function get($name) {
    return self::$storage[$name];
  }
}



/**
 * Base class for all generated LR parsers.
 */
class yyparse {

  /**
   * Productions table (generated by Syntax tool).
   *
   * Format of a row:
   *
   * [ <NonTerminal Index>, <RHS.length>, <semanticActionName> ]
   */
  private static $productions = [[-1,1,'_handler1'],
[0,1,'_handler2'],
[1,1,'_handler3'],
[1,1,'_handler4'],
[2,4,'_handler5'],
[2,6,'_handler6'],
[2,6,'_handler7'],
[2,6,'_handler8'],
[3,1,'_handler9'],
[3,1,'_handler10'],
[3,1,'_handler11'],
[3,1,'_handler12']];

  /**
   * Tokens map (from token type to encoded index, autogenerated).
   */
  private static $tokens = array('NOT' => "4", '(' => "5", ')' => "6", 'EQ' => "7", ',' => "8", 'AND' => "9", 'OR' => "10", 'NUMBER' => "11", 'STRING' => "12", 'FIELDNAME' => "13", 'NULL' => "14", '$' => "15");

  /**
   * Parsing table (generated by Syntax tool).
   */
  private static $table = array(array('0' => 1, '2' => 2, '4' => "s3", '7' => "s4", '9' => "s5", '10' => "s6"), array('15' => "acc"), array('15' => "r1"), array('5' => "s7"), array('5' => "s16"), array('5' => "s21"), array('5' => "s26"), array('1' => 8, '2' => 9, '3' => 10, '4' => "s3", '7' => "s4", '9' => "s5", '10' => "s6", '11' => "s11", '12' => "s12", '13' => "s13", '14' => "s14"), array('6' => "s15"), array('6' => "r2", '8' => "r2"), array('6' => "r3", '8' => "r3"), array('6' => "r8", '8' => "r8"), array('6' => "r9", '8' => "r9"), array('6' => "r10", '8' => "r10"), array('6' => "r11", '8' => "r11"), array('6' => "r4", '8' => "r4", '15' => "r4"), array('1' => 17, '2' => 9, '3' => 10, '4' => "s3", '7' => "s4", '9' => "s5", '10' => "s6", '11' => "s11", '12' => "s12", '13' => "s13", '14' => "s14"), array('8' => "s18"), array('1' => 19, '2' => 9, '3' => 10, '4' => "s3", '7' => "s4", '9' => "s5", '10' => "s6", '11' => "s11", '12' => "s12", '13' => "s13", '14' => "s14"), array('6' => "s20"), array('6' => "r5", '8' => "r5", '15' => "r5"), array('1' => 22, '2' => 9, '3' => 10, '4' => "s3", '7' => "s4", '9' => "s5", '10' => "s6", '11' => "s11", '12' => "s12", '13' => "s13", '14' => "s14"), array('8' => "s23"), array('1' => 24, '2' => 9, '3' => 10, '4' => "s3", '7' => "s4", '9' => "s5", '10' => "s6", '11' => "s11", '12' => "s12", '13' => "s13", '14' => "s14"), array('6' => "s25"), array('6' => "r6", '8' => "r6", '15' => "r6"), array('1' => 27, '2' => 9, '3' => 10, '4' => "s3", '7' => "s4", '9' => "s5", '10' => "s6", '11' => "s11", '12' => "s12", '13' => "s13", '14' => "s14"), array('8' => "s28"), array('1' => 29, '2' => 9, '3' => 10, '4' => "s3", '7' => "s4", '9' => "s5", '10' => "s6", '11' => "s11", '12' => "s12", '13' => "s13", '14' => "s14"), array('6' => "s30"), array('6' => "r7", '8' => "r7", '15' => "r7"));

  /**
   * Parsing stack.
   */
  private static $stack = [];

  /**
   * Result of a semantic action (used as `$$`).
   */
  private static $__ = null;

  /**
   * Result location (used as `@$`).
   */
  private static $__loc = null;

  /**
   * Parser event callbacks.
   */
  private static $on_parse_begin = null;
  private static $on_parse_end = null;

  /**
   * Matched token text.
   */
  public static $yytext = '';

  /**
   * Matched token length.
   */
  public static $yyleng = 0;

  /**
   * End of file symbol.
   */
  const EOF = '$';

  /**
   * Tokenizer instance.
   */
  private static $tokenizer = null;

  private static function _handler1($_1) {
yyparse::$__ = $_1;
}

private static function _handler2($_1) {
yyparse::$__ = $_1;
}

private static function _handler3($_1) {
yyparse::$__ = $_1;
}

private static function _handler4($_1) {
yyparse::$__ = $_1;
}

private static function _handler5($_1,$_2,$_3,$_4) {
yyparse::$__ = new Tokens\NotExpr($_3);
}

private static function _handler6($_1,$_2,$_3,$_4,$_5,$_6) {
yyparse::$__ = new Tokens\EqExpr($_3, $_5);
}

private static function _handler7($_1,$_2,$_3,$_4,$_5,$_6) {
yyparse::$__ = new Tokens\AndExpr($_3, $_5);
}

private static function _handler8($_1,$_2,$_3,$_4,$_5,$_6) {
yyparse::$__ = new Tokens\OrExpr($_3, $_5);
}

private static function _handler9($_1) {
yyparse::$__ = new Tokens\IntVal($_1);
}

private static function _handler10($_1) {
yyparse::$__ = new Tokens\StrVal($_1);
}

private static function _handler11($_1) {
yyparse::$__ = new Tokens\FldVal($_1);
}

private static function _handler12($_1) {
yyparse::$__ = new Tokens\NullVal();
}

  private static $shouldCaptureLocations = false;

  private static function yyloc($start, $end) {
    // Epsilon doesn't produce location.
    if (!$start || !$end) {
      return !$start ? $end : $static;
    }

    return array(
      'startOffset' => $start['startOffset'],
      'endOffset' => $end['endOffset'],
      'startLine' => $start['startLine'],
      'endLine' => $end['endLine'],
      'startColumn' => $start['startColumn'],
      'endColumn' => $end['endColumn'],
    );
  }

  public static function setTokenizer($tokenizer) {
    self::$tokenizer = $tokenizer;

    // Also set it on `yy` so semantic actions can access the tokenizer.
    yy::$tokenizer = $tokenizer;
    yy::$lexer = $tokenizer;
  }

  public static function getTokenizer() {
    return self::$tokenizer;
  }

  public static function setOnParseBegin($on_parse_begin) {
    self::$on_parse_begin = $on_parse_begin;
  }

  public static function setOnParseEnd($on_parse_end) {
    self::$on_parse_end = $on_parse_end;
  }

  public static function parse($string) {
    if (self::$on_parse_begin) {
      $on_parse_begin = self::$on_parse_begin;
      $on_parse_begin($string);
    }

    $tokenizer = self::getTokenizer();

    if (!$tokenizer) {
      throw new SyntaxException(`Tokenizer is not provided.`);
    }

    $tokenizer->initString($string);

    $stack = &self::$stack;
    $stack = ['0'];

    $tokens = &self::$tokens;
    $table = &self::$table;
    $productions = &self::$productions;

    $token = $tokenizer->getNextToken();
    $shifted_token = null;

    do {
      if (!$token) {
        self::unexpectedEndOfInput();
      }

      $state = end($stack);
      $column = $tokens[$token['type']];

      if (!isset($table[$state][$column])) {
        self::unexpectedToken($token);
      }
      $entry = $table[$state][$column];

      if ($entry[0] === 's') {
        $loc = null;

        if (self::$shouldCaptureLocations) {
          $loc = array(
            'startOffset' => $token['startOffset'],
            'endOffset'=> $token['endOffset'],
            'startLine' => $token['startLine'],
            'endLine' => $token['endLine'],
            'startColumn' => $token['startColumn'],
            'endColumn' => $token['endColumn'],
          );
        }

        array_push(
          $stack,
          array(
            'symbol' => $tokens[$token['type']],
            'semanticValue' => $token['value'],
            'loc' => $loc,
          ),
          intval(substr($entry, 1))
        );
        $shifted_token = $token;
        $token = $tokenizer->getNextToken();
      } else if ($entry[0] === 'r') {
        $production_number = intval(substr($entry, 1));
        $production = $productions[$production_number];
        $has_semantic_action = count($production) > 2;
        $semantic_value_args = $has_semantic_action ? [] : null;

        $location_args = (
          $has_semantic_action && self::$shouldCaptureLocations
            ? []
            : null
        );

        if ($production[1] !== 0) {
          $rhs_length = $production[1];
          while ($rhs_length-- > 0) {
            array_pop($stack);
            $stack_entry = array_pop($stack);

            if ($has_semantic_action) {
              array_unshift(
                $semantic_value_args,
                $stack_entry['semanticValue']
              );

              if ($location_args !== null) {
                array_unshift(
                  $location_args,
                  $stack_entry['loc']
                );
              }
            }
          }
        }

        $reduce_stack_entry = array('symbol' => $production[0]);

        if ($has_semantic_action) {
          self::$yytext = $shifted_token ? $shifted_token['value'] : null;
          self::$yyleng = $shifted_token ? strlen($shifted_token['value']) : null;

          forward_static_call_array(
            array('self', $production[2]),
            $location_args !== null
              ? array_merge($semantic_value_args, $location_args)
              : $semantic_value_args
          );

          $reduce_stack_entry['semanticValue'] = self::$__;

          if ($location_args !== null) {
            $reduce_stack_entry['loc'] = self::$__loc;
          }
        }

        $next_state = end($stack);
        $symbol_to_reduce_with = $production[0];

        array_push(
          $stack,
          $reduce_stack_entry,
          $table[$next_state][$symbol_to_reduce_with]
        );
      } else if ($entry === 'acc') {
        array_pop($stack);
        $parsed = array_pop($stack);

        if (count($stack) !== 1 ||
            $stack[0] !== '0' ||
            $tokenizer->hasMoreTokens()) {
          self::unexpectedToken($token);
        }

        $parsed_value = array_key_exists('semanticValue', $parsed)
          ? $parsed['semanticValue']
          : true;

        if (self::$on_parse_end) {
          $on_parse_end = self::$on_parse_end;
          $on_parse_end($parsed_value);
        }

        return $parsed_value;
      }

    } while ($tokenizer->hasMoreTokens() || count($stack) > 1);
  }

  private static function unexpectedToken($token) {
    if ($token['type'] === self::EOF) {
      self::unexpectedEndOfInput();
    }

    self::getTokenizer()->throwUnexpectedToken(
      $token['value'],
      $token['startLine'],
      $token['startColumn']
    );
  }

  private static function unexpectedEndOfInput() {
    self::parseError('Unexpected end of input.');
  }

  private static function parseError($message) {
    throw new SyntaxException('SyntaxError: ' . $message);
  }
}


/**
 * Generic tokenizer used by the parser in the Syntax tool.
 *
 * https://www.npmjs.com/package/syntax-cli
 *
 * See `--custom-tokinzer` to skip this generation, and use a custom one.
 */

class Tokenizer {
  private static $lexRules = [['/^\\s+/', '_lex_rule1'],
['/^not/', '_lex_rule2'],
['/^eq/', '_lex_rule3'],
['/^and/', '_lex_rule4'],
['/^or/', '_lex_rule5'],
['/^NULL/', '_lex_rule6'],
['/^,/', '_lex_rule7'],
['/^\\(/', '_lex_rule8'],
['/^\\)/', '_lex_rule9'],
['/^\\d+(\\.\\d+)?/', '_lex_rule10'],
['/^"(\\\\"|[^"])*"/', '_lex_rule11'],
['/^\'(\\\\\'|[^\'])*\'/', '_lex_rule12'],
['/^[A-Z]\\w+(\\.[A-Z]\\w+)*/', '_lex_rule13']];
  private static $lexRulesByConditions = array('INITIAL' => array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12));

  private $states = array();
  private $string = '';
  private $stringLen = 0;
  private $cursor = 0;
  private $tokensQueue = array();

  /**
   * Line-based location tracking.
   */
  private $currentLine = 1;
  private $currentColumn = 0;
  private $currentLineBeginOffset = 0;

  /**
   * Location data of a matched token.
   */
  private $tokenStartOffset = 0;
  private $tokenEndOffset = 0;
  private $tokenStartLine = 0;
  private $tokenEndLine = 0;
  private $tokenStartColumn = 0;
  private $tokenEndColumn = 0;

  private static $EOF_TOKEN = array(
    'type' => yyparse::EOF,
    'value' => '',
  );

  private function _lex_rule1() {
# skip whitespace;
}

private function _lex_rule2() {
return 'NOT';
}

private function _lex_rule3() {
return 'EQ';
}

private function _lex_rule4() {
return 'AND';
}

private function _lex_rule5() {
return 'OR';
}

private function _lex_rule6() {
return 'NULL';
}

private function _lex_rule7() {
return ',';
}

private function _lex_rule8() {
return '(';
}

private function _lex_rule9() {
return ')';
}

private function _lex_rule10() {
return 'NUMBER';
}

private function _lex_rule11() {
return 'STRING';
}

private function _lex_rule12() {
return 'STRING';
}

private function _lex_rule13() {
return 'FIELDNAME';
}

  public function initString($string) {
    $this->string = $string;
    $this->stringLen = strlen($this->string);
    $this->cursor = 0;
    $this->states = array('INITIAL');
    $this->tokensQueue = array();

    $this->currentLine = 1;
    $this->currentColumn = 0;
    $this->currentLineBeginOffset = 0;

    /**
     * Location data of a matched token.
     */
    $this->tokenStartOffset = 0;
    $this->tokenEndOffset = 0;
    $this->tokenStartLine = 0;
    $this->tokenEndLine = 0;
    $this->tokenStartColumn = 0;
    $this->tokenEndColumn = 0;
  }

  public function getStates() {
    return $this->states;
  }

  public function getCurrentState() {
    return $this->states[count($this->states) - 1];
  }

  public function pushState($state) {
    $this->states[] = $state;
  }

  public function begin($state) {
    $this->pushState(state);
  }

  public function popState() {
    if (count($this->states) > 1) {
      return array_pop($this->states);
    }
    return $this->states[0];
  }

  public function getNextToken() {
    if (count($this->tokensQueue) > 0) {
      return $this->toToken(array_shift($this->tokensQueue));
    }

    if (!$this->hasMoreTokens()) {
      return self::$EOF_TOKEN;
    }

    $string = substr($this->string, $this->cursor);
    $lexRulesForState = static::$lexRulesByConditions[$this->getCurrentState()];

    foreach ($lexRulesForState as $lex_rule_index) {
      $lex_rule = self::$lexRules[$lex_rule_index];

      $matched = $this->match($string, $lex_rule[0]);

      // Manual handling of EOF token (the end of string). Return it
      // as `EOF` symbol.
      if (!$string && $matched === '') {
        $this->cursor++;
      }

      if ($matched !== null) {
        yyparse::$yytext = $matched;
        yyparse::$yyleng = strlen($matched);
        $token = call_user_func(array($this, $lex_rule[1]));
        if (!$token) {
          return $this->getNextToken();
        }

        // If multiple tokens are returned, save them to return
        // on next `getNextToken` call.
        if (is_array($token)) {
          $tokens_to_queue = array_slice($token, 1);
          $token = $token[0];
          if (count($tokens_to_queue) > 0) {
            array_unshift($this->tokensQueue, ...$tokens_to_queue);
          }
        }

        return $this->toToken($token, yyparse::$yytext);
      }
    }

    if ($this->isEOF()) {
      $this->cursor++;
      return self::$EOF_TOKEN;
    }

    $this->throwUnexpectedToken(
      $string[0],
      $this->currentLine,
      $this->currentColumn
    );
  }

  /**
   * Throws default "Unexpected token" exception, showing the actual
   * line from the source, pointing with the ^ marker to the bad token.
   * In addition, shows `line:column` location.
   */
  public function throwUnexpectedToken($symbol, $line, $column) {
    $line_source = explode("\n", $this->string)[$line - 1];

    $pad = str_repeat(' ', $column);
    $line_data = "\n\n" . $line_source . "\n" . $pad . "^\n";

    throw new SyntaxException(
      $line_data . 'Unexpected token: "' . $symbol . '" at ' .
      $line . ':' . $column . '.'
    );
  }

  private function captureLocation($matched) {
    // Absolute offsets.
    $this->tokenStartOffset = $this->cursor;

    // Line-based locations, start.
    $this->tokenStartLine = $this->currentLine;
    $this->tokenStartColumn = $this->tokenStartOffset - $this->currentLineBeginOffset;

    // Extract `\n` in the matched token.
    preg_match_all('/\n/', $matched, $nl_matches, PREG_OFFSET_CAPTURE);
    $nl_match = $nl_matches[0];

    if (count($nl_match) > 0) {
      foreach ($nl_match as $nl_match_data) {
        $this->currentLine++;
        // Offset is at index 1.
        $this->currentLineBeginOffset = $this->tokenStartOffset +
          $nl_match_data[1] + 1;
      }
    }

    $this->tokenEndOffset = $this->cursor + strlen($matched);

    // Line-based locations, end.
    $this->tokenEndLine = $this->currentLine;
    $this->tokenEndColumn = $this->currentColumn =
      ($this->tokenEndOffset - $this->currentLineBeginOffset);
  }

  private function toToken($token, $yytext = '') {
    return array(
      'type' => $token,
      'value' => $yytext,
      'startOffset' => $this->tokenStartOffset,
      'endOffset' => $this->tokenEndOffset,
      'startLine' => $this->tokenStartLine,
      'endLine' => $this->tokenEndLine,
      'startColumn' => $this->tokenStartColumn,
      'endColumn' => $this->tokenEndColumn,
    );
  }

  public function isEOF() {
    return $this->cursor == $this->stringLen;
  }

  public function hasMoreTokens() {
    return $this->cursor <= $this->stringLen;
  }

  private function match($string, $regexp) {
    preg_match($regexp, $string, $matches);
    if (count($matches) > 0) {
      $matched = $matches[0];
      $this->captureLocation($matched);
      $this->cursor += strlen($matched);
      return $matched;
    }
    return null;
  }
}

yyparse::setTokenizer(new Tokenizer());


class Parser extends yyparse {}
